---
title: "HW3 Maps"
author: "Owen Stevenson"
date: "9/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(shiny)
library(dplyr)
library(tidyverse)
library(googlesheets)
library(ggmap)
require(leaflet)
require(purrr)
require(stringr)
require(rgdal)
require(rgeos)
require(sp)
require(leaflet.extras)
```

```{r}
statenames <- read.csv(url("https://raw.githubusercontent.com/jasonong/List-of-US-States/master/states.csv")) %>%
  mutate(State = as.character(State))

key <- extract_key_from_url("https://docs.google.com/spreadsheets/d/17ps4aqRyaIfpu7KdGsy2HRZaaQiXUfLrpUbaR9yS51E/")
# google_ws <- gs_key(key)
data <- read_csv("Whose Heritage 2018 Master Sheet - Whose Heritage 2018 Master 7.27.18.csv")
colnames(data) <- make.names(colnames(data))

# split Coordinates row into Lat & Lon
data <- mutate(data, Dedicated.Num = as.numeric(data$Year.Dedicated))
coords <- data.frame(do.call('rbind',strsplit(as.character(data$Coordinates), ',', fixed = T))) %>%
  transmute(lat = as.character(X1), lon = as.character(trimws(X2))) %>%
  mutate(lat = as.numeric(lat), lon = as.numeric(lon))

data <- mutate(data, lat = coords$lat, lon = coords$lon)

typeof(data$lat[1])
state.load <- readOGR("gz_2010_us_040_00_5m.json")
test <- distinct(select(data, "State", "Side"))

## function from https://github.com/tidyverse/dplyr/issues/2278 ## didn't end up needing
strict_left_join <- function(x, y, by = NULL, ...){
  by <- common_by(by, x, y)
  if(any(duplicated(y[by$y]))) {
    stop("Duplicate values in foreign key")
  } else left_join(x, y, by = by, ...)
}

data$State <- as.character(data$State)

## Joins in order to merge State info to shapefile
state.load@data <- 
  state.load@data %>%
  inner_join(statenames, by = c("NAME" = "State")) %>%
  left_join(test, by = c("Abbreviation" = "State"))


test <- select(data, "State", "Side")
pal <- colorFactor(palette = c("blue","red","yellow","gray"), levels = c("North","South","Border","Not a State"))

glimpse(state.load@data)
### Confederate Monuments
m <- 
  state.load %>%
  leaflet() %>%
  addProviderTiles('OpenStreetMap.BlackAndWhite', group = "Black & White") %>%
  addProviderTiles('Stamen.Watercolor', group = "Watercolor") %>%
  addCircleMarkers(lng = data$lon, lat = data$lat, popup = data$Name, clusterOptions = markerClusterOptions()) %>%
  addLayersControl(
    baseGroups = c("Black & White","Watercolor"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addPolygons(weight = 1, color = "grey", label = ~paste0(NAME, " - Side: ", Side), highlight = highlightOptions(weight = 3, color = "red" , bringToFront = TRUE), fillColor = ~pal(Side), fill = ~pal(Side)) %>%
  addLegend(title = "Confederate Monuments & Civil War State Allegiences", position = "bottomright", pal = pal, values = c("North","South","Border","Not a State")) %>%
  setView(lng = -98.35, lat = 39.8283, zoom = 3)

m
```

```{r}
## Line file map - Railroads
railroads.load <-  readOGR("lasses/Fall 2018/R Shiny for Operations Management/HW/HW3 file/RR1826-1911Modified0509161/RR1826-1911Modified050916.shp", layer = "RR1826-1911Modified050916", GDAL1_integer64_policy = TRUE)

# Comment or delete broken lines of code!
railroads2.load <- readOGR("./tl_2018_us_rails/tl_2018_us_rails.shp", layer = "tl_2018_us_rails", GDAL1_integer64_policy = TRUE)

# glimpse(railroads.load)
# m2 <- 
#   railroads.load %>%
#   leaflet() %>%
#   addTiles() %>%
#   addPolygons()
  
# This one actually works
# Which one?!? Above or below? Because the data for the first map didn't load...

m3 <- 
  railroads2.load %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons() #%>%
  #addLegend(title = "Railroads of the US")

m3
```




